apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: myapp
  namespace: cert-manager
spec:
  secretName: myapp-tls-staging
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  organization:
    - jetstack
  keySize: 2048
  keyAlgorithm: rsa
  keyEncoding: pkcs1
  usages:
    - server auth
    - client auth
  issuerRef:
    name: myapp-letsncrypt-staging
    kind: Issuer
  commonName: myapp.xxxx.com
  dnsNames:
    - myapp.xxxx.com
